apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: billing-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: billing.local
    http:
      paths:

      # Client Service
      - path: /api/clients(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: client-service
            port:
              number: 3000

      # Invoice Service
      - path: /api/invoices(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: invoice-service
            port:
              number: 3001

      # Payment Service
      - path: /api/payments(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: payment-service
            port:
              number: 3002

      # Report Service
      - path: /api/reports(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: report-service
            port:
              number: 3003
